### ISSUE TITLE
About Mobile Responsiveness

### ISSUE THREAD

**Issue by seanquiambao** [acm-ucr/h4b-website#110]
![image](https://github.com/user-attachments/assets/08879b62-5a0d-4b63-929f-5716988ed300)

- Page is almost mobile responsive, but we should make the text a little bit smaller

![image](https://github.com/user-attachments/assets/ff012516-d4eb-4d0e-8f0b-68baca876bf8)

reference from the isa website

**Comment by ALE00111** [comment]
This is my first time doing a mobile responsive issue and I was wondering when we say that the text should be mobile responsive, do you mean that it should be a decent size for all devices like the ones in the drop down menu? 
![image](https://github.com/user-attachments/assets/88693f6c-384a-4d52-8bc6-3f0972ecb9e6)

**Comment by seanquiambao** [comment]
> This is my first time doing a mobile responsive issue and I was wondering when we say that the text should be mobile responsive, do you mean that it should be a decent size for all devices like the ones in the drop down menu? ![image](https://private-user-images.githubusercontent.com/117538724/352636629-88693f6c-384a-4d52-8bc6-3f0972ecb9e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMjIyOTEsIm5iZiI6MTcyMjAyMTk5MSwicGF0aCI6Ii8xMTc1Mzg3MjQvMzUyNjM2NjI5LTg4NjkzZjZjLTM4NGEtNGQ1Mi04YmM2LTNmMDk3MmVjYjllNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxOTI2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWMxZjA5ZTQ0MzRiOThmYWJjMTBkMTI1NzdkYjYwOGVkNTAyNGRlMTAzMzQ4NGQ2YzYwMDkzM2U1OGNkOWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YJaV0lMcfQQTeNzvK2tY_yTTJGMZwLsNqReX5SYiGFU)

yeah the text should be a bit smaller on mobile view. you can play around with the width, but as long as it fits with most mobile screen sizes it should be fine.
