### ISSUE TITLE
Implement Connect.jsx

### ISSUE THREAD

**Issue by seanquiambao** [acm-ucr/h4b-website#31]
<img width="384" alt="image" src="https://github.com/acm-ucr/h4b-website/assets/91030482/cf00131b-17a8-4ba4-89a8-8879295aa095">

Component:
- Should be under /components/support
- Use React Icons documentation to find the appropriate icons.
- Icon is a link that directs users to the page.
- Create a data file under /data/support called Socials.js
- contains a list of social media links with its name, icon, and link.
- add the name of the social media at the bottom of each icon.

References:
https://acm-ucr.github.io/docusaurus/docs/react/mapping-filtering
https://react-icons.github.io/react-icons/

**Comment by ALE00111** [comment]
I can't currently find the file called support? Is it in a different folder?

**Comment by seanquiambao** [comment]
> I can't currently find the file called support? Is it in a different folder?

you'll have to create a folder called support (inside data), and create the SOCIALS.js under /data/support. unless you're talking about the components, then it should be there already.

**Comment by seanquiambao** [comment]
> > I can't currently find the file called support? Is it in a different folder?
> 
> you'll have to create a folder called support (inside data), and create the SOCIALS.js under /data/support. unless you're talking about the components, then it should be there already.

oh wait there's neither 😭😭

just create a folder if it doesn't exist. for folder names, it should be lowercased and single word

**Comment by ALE00111** [comment]
> > > I can't currently find the file called support? Is it in a different folder?
> > 
> > 
> > you'll have to create a folder called support (inside data), and create the SOCIALS.js under /data/support. unless you're talking about the components, then it should be there already.
> 
> oh wait there's neither 😭😭
> 
> just create a folder if it doesn't exist. for folder names, it should be lowercased and single word

Also, should this be done with a map in SOCIALS? Like in a page in the support app, I import data from socials and that data is used in the support component.

**Comment by seanquiambao** [comment]
Yes you would use the mapping function to map through the array SOCIALS
